#!/bin/bash

CLOUD_RUN_URL="https://cloudrun-srv-6thgagxxya-uc.a.run.app"

texts=("The sun is shining, and life is good!"
       "Feeling grateful for simple joys."
       "Just had the best cup of coffee ever!"
       "Things could be worse, I suppose."
       "Just feeling a bit meh today."
       "It's one of those days..."
       "Did you know flamingos are pink because of their diet?"
       "I wonder what's for dinner tonight..."
       "Random thought of the day: clouds are fluffy."
       "Missing someone special today."
       "Heart feels heavy."
       "Just need a hug."
       "Excited for the weekend!"
       "Feeling a bit under the weather."
       "The sky is a beautiful shade of blue."       
       "The sun is making the city glow today."
       "Just finished a Zoom meeting that could've been an email."
       "Why are there so many brands of toothpaste? It's just toothpaste!"
       "Feeling nostalgic for old cartoons."
       "I wonder if dogs dream of chasing squirrels."
       "This coffee is the only thing keeping me going."
       "The Green Park avenue is a nice place for a walk, don't you think?"
       "Sometimes, silence is the best answer."
       "I have my doubts about how important Skittles are for society."
       "Is it just me, or are pigeons getting bolder?"
       "The smell of freshly cut grass is pure happiness."
       "I'm convinced my cat is plotting world domination."
       "The clouds look like fluffy sheep today."
       "Why do socks always disappear in the laundry?"
       "This song takes me back to high school."
       "Feeling grateful for this moment."
       "The internet is a weird and wonderful place."
       "I wonder what aliens would think of our planet."
       "Seriously considering becoming a plant parent."
       "Remember when we used to rent movies from Blockbuster?"
       "The moon looks extra bright tonight."
       "I'm convinced my phone is listening to my conversations."
       "Why do we still have potatoes that are not sweet potatoes?"
       "That awkward moment when you wave at someone who wasn't waving at you."
       "Just ordered way too much food... but no regrets."
       "I wish I could teleport to the beach right now."
       "What if cats are actually tiny aliens sent to observe us?"
       "This tea tastes like warm hugs."
       "I'm starting to think my houseplant is judging me."
       )

for text in "${texts[@]}"; do
    curl -X POST -H "Content-Type: application/json" -d "{\"text\": \"$text\"}" "$CLOUD_RUN_URL"
done
