steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
   - '-c'
   - >-
    docker build --no-cache -t REGION-docker.pkg.dev/PROJECT_ID/recaptcha-heroes-docker-repo-SHORTCOMMIT/recaptcha-heroes-demo-image:COMMITID 
    --build-arg projectId=PROJECT_NUMBER --build-arg comitid=COMMITID --build-arg apikey=$$APISECRET 
    --build-arg v3key=V3KEY --build-arg v2key=V2KEY 
    --build-arg test2key=TEST2KEY --build-arg test8key=TEST8KEY 
    --build-arg expresskey=EXPRESSKEY . -f Dockerfile
  automapSubstitutions: true
  id: Build
  entrypoint: bash
  secretEnv:
      - APISECRET
- name: gcr.io/cloud-builders/docker
  args:
    - push
    - >-
      REGION-docker.pkg.dev/PROJECT_ID/recaptcha-heroes-docker-repo-SHORTCOMMIT/recaptcha-heroes-demo-image:COMMITID
  id: Push
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args:
    - run
    - services
    - update
    - recaptcha-demo-service-SHORTCOMMIT
    - '--platform=managed'
    - >-
      --image=REGION-docker.pkg.dev/PROJECT_ID/recaptcha-heroes-docker-repo-SHORTCOMMIT/recaptcha-heroes-demo-image:COMMITID
    - >-
      --labels=managed-by=gcp-cloud-build-deploy-cloud-run
    - '--region=REGION'
    - '--quiet'
  id: Deploy
  entrypoint: gcloud
images:
  - 'REGION-docker.pkg.dev/PROJECT_ID/recaptcha-heroes-docker-repo-SHORTCOMMIT/recaptcha-heroes-demo-image:COMMITID'
logsBucket: 'gs://LOG_BUCKET'
serviceAccount: 'projects/PROJECT_ID/serviceAccounts/SERVICE_ACCOUNT'
options:
  logging: GCS_ONLY
availableSecrets:
  secretManager:
    - versionName: >-
        projects/PROJECT_NUMBER/secrets/recaptcha-heroes-apikey-SHORTCOMMIT/versions/latest
      env: APISECRET